spring:
  application:
    name: ip-management


  redis:
    host: localhost
    port: 6379
    password:
    timeout: 10000
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:ip_management
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    operations-sorter: method



server:
  port: 9090

external-api:
  geo-ip-inf:
    url: http://api.ipapi.com/api/{ip}
    access_key: 77e772975cc1ffdbd5483509cabdeca0
  country-inf:
    url: https://restcountries.eu/rest/v2/alpha/{code}
  currency-inf:
    url: http://data.fixer.io/api/latest
    access_key: 980a2bd55f4c15a08291aca24757f4cf

internal:
  crontab-reset: 0 0 * * * ?

